#Pytorch For Maths 

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing . Deep learning Applications can take place in pytorch also . Functions that i chosen are Mathematical Functions , One would ask why would we use Pytorch for these functions , why not Numpy when these functions exist in Numpy module which is better for numerical calculations . Pytorch uses GPU for processing its computations , Numpy doesn't which gives Pytorch edge for larger inputs.

- torch.arange()
- torch.bitwise_xor()
- torch.sqrt()
- torch.unique()
- torch.gcd()

Before we begin, let's install and import PyTorch

In [3]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [4]:
# Import torch and other required modules
import torch

## Function 1 - torch.arange()

Returns a 1-D tensor with values from the interval [start, end) taken with common difference step beginning from start.

**Parameters**

**`start (Number)`** – the starting value for the set of points. Default: 0.

**`end (Number)`** – the ending value for the set of points

**`step (Number)`** – the gap between each pair of adjacent points. Default: 1.

In [5]:
# Example 1 - working 
torch.arange(5,10,1)

tensor([5, 6, 7, 8, 9])

Start is mentioned as 5 and end as 10 , step is 1 so 5 valued tensor will be created starting from 5 to 9 (10 is not uncluded)

In [6]:
# Example 2 - working
torch.arange(5.5,100,5)

tensor([ 5.5000, 10.5000, 15.5000, 20.5000, 25.5000, 30.5000, 35.5000, 40.5000,
        45.5000, 50.5000, 55.5000, 60.5000, 65.5000, 70.5000, 75.5000, 80.5000,
        85.5000, 90.5000, 95.5000])

Tensor Created will multiple values each at step 5 

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(5,1,1)

RuntimeError: ignored

Reason for Runtime Error - Start is smaller then end 

This function is used to get a torch which is equaly spaced between two number

Let's save our work using Jovian before continuing.

In [8]:
!pip install jovian --upgrade --quiet

In [9]:
import jovian

In [10]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/suryansh-may/01-tensor-operations


'https://jovian.ai/suryansh-may/01-tensor-operations'

## Function 2 - torch.bitwise_xor()

XOR is an operation which takes place in the bitwise level . if there is different type of bit , then it will result in 1 otherwise result in 0.


In [11]:
# Example 1 - working
torch.bitwise_xor(torch.tensor([-1, -2, 3], dtype=torch.int8), torch.tensor([1, 0, 3], dtype=torch.int8))

tensor([-2, -2,  0], dtype=torch.int8)

When -1 and 1 are converted in binary and theirr XOR is done , it results in 00010 which is 2 in decimal

In [12]:
# Example 2 - working
torch.bitwise_xor(torch.tensor([False,True,True]), torch.tensor([True,False,True]))

tensor([ True,  True, False])

True And False give True and others False

In [13]:
torch.bitwise_xor(torch.tensor([True, True, False]), torch.tensor([2, True, False]))

RuntimeError: ignored

Runtime Error - XOR operation can not take place between booleans and intergers

XOR is useful as it tells about distinct bits in the binary position of both the operands

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 3 - torch.unique()

Returns the unique elements of the input tensor.

In [15]:
# Example 1 - working
torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.long))

tensor([1, 2, 3])

3 exists two times therefore only one is returned 

In [21]:
# Example 2 - working
torch.unique(torch.tensor([1,5,2,1,5,7,4,8,2,1,5,8,9,5,1,2,3], dtype=torch.long), sorted=True )

tensor([1, 2, 3, 4, 5, 7, 8, 9])

Unique Elements and Sorted tensor is returned

In [44]:
torch.unique(torch.tensor([[[ 6.,  2.,  5.,  3.],
        [ 4.,  1.,  9.,  8.],
        [ 6.,  5.,  4.,  7.]],

       [[ 2.,  6.,  6.,  6.],
        [ 7.,  1.,  23.,  4. ,5.],
        [ 9.,  10.,  4.,  8.]]]))

ValueError: ignored

lenght needs to be same

To return only Unique elements in tensor removing copy of the same element 

In [45]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/suryansh-may/01-tensor-operations


'https://jovian.ai/suryansh-may/01-tensor-operations'

## Function 4 - torch.gcd()

Computes the element-wise greatest common divisor (GCD) of input and other.

Both input and other must have integer types.

In [46]:
# Example 1 - working
a = torch.tensor([5, 10, 15])
b = torch.tensor([3, 4, 5])
torch.gcd(a, b)

tensor([1, 2, 5])

Return a tensor containing GCD of the input tensor passed based on index 

In [48]:
# Example 2 - working
c = torch.tensor([3])
torch.gcd(a, c)

tensor([1, 1, 3])

Tensor gets broadcasted to return GCD of each index 

In [49]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.tensor([3,4])
torch.gcd(a, c)

RuntimeError: ignored

Cannot be Broadcasted together (mismatch)

Torch.gcd can help in finding GCD, LCM , Multiplication of elements and is very useful in mathematical operations

In [50]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/suryansh-may/01-tensor-operations


'https://jovian.ai/suryansh-may/01-tensor-operations'

## Function 5 - torch.sign()

Returns a new tensor with the signs of the elements of input

In [52]:
# Example 1 - working
a = torch.tensor([0.7, -1.2, 0., 2.3])
torch.sign(a)

tensor([ 1., -1.,  0.,  1.])

1 indicates positive value at that index , -1 negative and 0 tells that the element at that index is 0

In [53]:
# Example 2 - working
a = torch.tensor([1.7, -3.2, 0., 2.3])
torch.sign(a)

tensor([ 1., -1.,  0.,  1.])

Similarly here as well

In [57]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([[0.7, -1.2 , 5.], [0., 2.3],[3,1]])
torch.sign(a)

ValueError: ignored

Lenght should be same

This function tells which index is postive and negative can help in debugging if lot of imput is there 

In [58]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/suryansh-may/01-tensor-operations


'https://jovian.ai/suryansh-may/01-tensor-operations'

## Conclusion

These were just some of the functions of pytorch , these functions are computed with GPU which helps them to be faster than the numpy operations of numpy module

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* Pytorch Github - https://github.com/pytorch
* Pytorch Tutorials - https://pytorch.org/tutorials/

In [60]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/suryansh-may/01-tensor-operations


'https://jovian.ai/suryansh-may/01-tensor-operations'